### ISSUE TITLE
FastAPI connector re-use of engine for high workloads

### ISSUE THREAD

**Issue by cw-optima-ovo** [GoogleCloudPlatform/cloud-sql-python-connector#772] opened 2023-06-27 16:06 UTC
### Question

I am currently experiencing issues with using the cloud sql python connector under heavy web traffic workloads inside a cloud run instance using FastAPI and SQLAlchemy. It seems the examples given are hitting Quota limits in the SQLAdmin API and I'd like to try and avoid that.

From what I understand, when the SQLAlchemy engine is created it makes two requests to the SQLAdmin API endpoint, this is expected however it's happening every time a request is made to the endpoint, not just when the endpoint is created.

How can I configure the cloud sql python connector to not make so many requests to the SQLAdmin API on every request to the FastAPI endpoint so I can use the connector with dozens (hundreds) of concurrent connections to a cloud sql instance?

### Code

```Python
from fastapi import FastAPI, Depends
from dotenv import load_dotenv
from google.cloud.sql.connector import Connector, IPTypes
from sqlalchemy import create_engine, text
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

load_dotenv()

db_user = open("/secrets/DBUSERSECRET/DBUSERSECRET", "r").read().strip()
db_name = open("/secrets/DBNAMESECRET/DBNAMESECRET", "r").read().strip()
cloudsql_conninstance = open("/secrets/SQLINSTANCE/SQLINSTANCE", "r").read().strip()
password = open("/secrets/PASSWORD/PASSWORD", "r").read().strip()


# Python Connector database connection function
def getconn():
    with Connector() as connector:
        conn = connector.connect(
            cloudsql_conninstance, # Cloud SQL Instance Connection Name
            "pg8000",
            user=db_user,
            password=password,
            db=db_name,
            ip_type= IPTypes.PRIVATE  # IPTypes.PRIVATE for private IP
        )
        return conn

SQLALCHEMY_DATABASE_URL = "postgresql+pg8000://"

engine = create_engine(
    SQLALCHEMY_DATABASE_URL , creator=getconn, pool_size=5
)

# create SQLAlchemy ORM session
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()


app = FastAPI()


@app.get("/")
async def root():
    return {"message": "Hello World"}

@app.get("/endpoint01")
def endpoint01( db: SessionLocal = Depends(get_db)):
    import aiohttp.client_exceptions
    try:
        sql_result = db.execute(text('SELECT MAX(ID) as max_id FROM test;'))
        for result in sql_result:
            max_id = result[0]
        returnmessage = f'max_id is: {max_id}'
        return({"message":returnmessage}, 200)
    except Exception as e:
        returnmessage = f'exception oh no - type({e}): {e}'
        return({"message":returnmessage}, 500)
```

### Additional Details

Discussed partly already with @jackwotherspoon in this thread:
https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/issues/764#issuecomment-1609648768

**Comment by jackwotherspoon** [comment] 2023-06-27 16:40
Hi @cw-optima-ovo ! Thanks for opening this issue 😄 

This is a great question and it has been something I have been thinking about recently myself. I believe I now see the issue and it is with our README samples, specifically the `getconn` function.

In trying to make the code samples as simple as possible I think I might have had some oversight surrounding the `create_engine`'s `creator` argument. ([SQLAlchemy creator](https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.create_engine.params.creator) arg) Originally I thought the `creator` function `getconn` was called once upon creating of the connection pool, however after re-visiting the documentation it seems this is not the case.

Per the [SQLAlchemy docs](https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.create_engine.params.creator):
> creator –
a callable which returns a DBAPI connection. This creation function will be passed to the underlying connection pool and will be used to create all new database connections. Usage of this function causes connection parameters specified in the URL argument to be bypassed.

It seems the `creator` function is called **on all new database connections** and not on pool creation 🤯 

Thus a new `Connector()` is being initialized on every endpoint call and not re-using a single `Connector` for an entire pool as intended. This is causing the inefficient use of Cloud SQL Admin API calls in your application.

I will update our samples to move the `Connector` initialization from inside the `getconn` to outside. This will allow the re-use of the single `Connector` object for each new database connection established as originally intended!

If you could try something along the lines of the following change I'd love to know if you see it solve your load testing issue:

```python
# helper function to properly manage Connector usage
def init_connection_pool(connector: Connector):
    def getconn():
        conn = connector.connect(
            cloudsql_conninstance, # Cloud SQL Instance Connection Name
            "pg8000",
            user=db_user,
            password=password,
            db=db_name,
            ip_type= IPTypes.PRIVATE  # IPTypes.PRIVATE for private IP
        )
        return conn

    engine = sqlalchemy.create_engine(
        "postgresql+pg8000://",
        creator=getconn,
        pool_size=5,
    )
    return engine

# create Connector outside getconn
connector = Connector()

# create connection pool engine
engine = init_connection_pool(connector)

# create SQLAlchemy ORM session
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# ...
```

Let me know if this fixes your errors and allows high traffic endpoint. If it does I will update our README samples accordingly 😄 Thanks for bringing this to our attention!

Have a great day! - Jack

**Comment by jcz-aml** [comment] 2023-06-28 03:41
@jackwotherspoon this is working great for us & resolved the quota exhaustion errors.  Makes sense too.  I would definitely suggest updating the samples!!

**Comment by cw-optima-ovo** [comment] 2023-06-28 10:23
Hey @jackwotherspoon after doing some heavy load testing this morning I can verify this works far better! No quota limits being hit either running remotely or locally, smooth sailing!
As a sidenote, I have noticed that the private IP connection is maybe 10x faster than the public connection to the cloud sql database - but obviously to anyone else reading this ... YMMV.

I've tested this with FastAPI but I was seeing the same problem with Flask, I assume the same solution you've proposed above could be implemented for Flask too so that'd be great to see the Readme updated for both.

Thanks again for your help with this, as always appreciate the help!

**Comment by jackwotherspoon** [comment] 2023-06-28 14:51
@jcz-aml Glad to hear the change seems to be resolving quota issues! 🎉 

I have opened PR #773 to help update the samples in the README to the proper and intended usage.

@cw-optima-ovo Yes Flask would also run into this if the `Connector` is initialized within the `getconn` function, my open PR also updates the Flask-SQLAlchemy sample.  

> As a sidenote, I have noticed that the private IP connection is maybe 10x faster than the public connection to the cloud sql database - but obviously to anyone else reading this ... YMMV.

Hmmm this is very interesting, I would not expect the difference between the two IP types to be so drastic. I will have to run some tests to look into this myself. There is no difference in the core library code between the two IP types that would cause this difference on the client side, so if there is a large difference in the performance, it would point at a server side issue would be my guess 🤔

**Comment by cw-optima-ovo** [comment] 2023-06-28 14:53
@jackwotherspoon this was my assumption as well, it's likely a server side problem in the routing to public that caused the response times to be so much slower - but interesting nonetheless!

**Closed** 2023-06-28 16:15 UTC
Labels: type: question, priority: p2

**Comment by jackwotherspoon** [comment] 2023-06-28 16:16
@jcz-aml @cw-optima-ovo README samples have been updated! 😄  

Thank you both very much for bringing this to my attention and helping make the Cloud SQL Python Connector better!

Have an awesome rest of your week!
