### ISSUE TITLE
TypeError: cannot unpack non-iterable function object --- pg8000 library connector

### ISSUE THREAD

**Issue by aiscience01** [GoogleCloudPlatform/cloud-sql-python-connector#548] opened 2022-11-27 02:26 UTC
Hello,

We are trying to use the Flask-SQLAlchamy using pg8000 connector as per the guide, and IAM authentication. Our code works with a local Postgres instance using the default driver library. We can also connect to GCP Cloud SQL (Postgres) using a direct database URL (not sql connector). However, when using this library-the Flask-SQLAlchemy extension- it seem pg8000 has an issue with setting the correct field size for a string field (creating a team name), and raises the following error:

 manager.dispatch.init_failure(self, args, kwargs)
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
 compat.raise_(
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
 raise exception
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/state.py", line 477, in _initialize_instance
 return manager.original_init(*mixed[1:], **kwargs)
 File "/home/app/flask/project/models/user.py", line 65, in __init__
 ModelProxy.teams.Team.create(team_name, self)
 File "/home/app/flask/project/models/__init__.py", line 158, in wrapper
 value = f(*args, **kwds)
 File "/home/app/flask/project/models/teams/team.py", line 68, in create
 db.session.commit()
 File "<string>", line 2, in commit
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
 self._transaction.commit(_to_root=self.future)
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 829, in commit
 self._prepare_impl()
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
 self.session.flush()
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3345, in flush
 self._flush(objects)
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3485, in _flush
 transaction.rollback(_capture_exception=True)
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
 compat.raise_(
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
 raise exception
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3445, in _flush
 flush_context.execute()
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
 rec.execute(self)
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
 util.preloaded.orm_persistence.save_obj(
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 244, in save_obj
 _emit_insert_statements(
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1221, in _emit_insert_statements
 result = connection._execute_20(
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
 return meth(self, args_10style, kwargs_10style, execution_options)
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
 return connection._execute_clauseelement(
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
 ret = self._execute_context(
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1731, in _execute_context
 context._set_input_sizes()
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1678, in _set_input_sizes
 self.root_connection._handle_dbapi_exception(
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2030, in _handle_dbapi_exception
 util.raise_(exc_info[1], with_traceback=exc_info[2])
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
 raise exception
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 1674, in _set_input_sizes
 self.dialect.do_set_input_sizes(
 File "/usr/local/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/pg8000.py", line 519, in do_set_input_sizes
 cursor.setinputsizes(
 File "/usr/local/lib/python3.9/site-packages/pg8000/dbapi.py", line 621, in setinputsizes
 oid, _ = self._c.py_types[size]
TypeError: cannot unpack non-iterable function object

Wondering what goes wrong, and if it's possible to use other popular adaptors instead of pg8000? 

## Environment

1. OS type and version: Debian 11
2. Python version: Python 3.9.15
3. Connector version:  pg8000 installed with: pip install "cloud-sql-python-connector[pg8000]"
4. Flask-SQLAlchemy extension

**Comment by upbrains-admin** [comment] 2022-11-29 23:40
Hi Jack, 

thank you. Yes, tried to use asyncpg but needed a lot of change to the code to make it work and was not working for us.

The code is not public (yet), but this part of our code is based on public repo. In settings.py (https://github.com/Sumukh/Ignite/blob/master/appname/settings.py), in the function ProdConf(), we replaced line 50 with your snippet of code for database URL definition:
 
gcp_pgsql_conn = get_gcp_connection()
SQLALCHEMY_DATABASE_URI = "postgresql+pg8000://"
SQLALCHEMY_ENGINE_OPTIONS = {
     "creator": get_gcp_connection
 }

And, defined the connector in function:

def get_gcp_connection():
   with Connector() as connector:
      conn = connector.connect(
          os.getenv('POSTGRESS_DB_INSTANCE'), # Cloud SQL Instance Connection Name
          "pg8000",
          user=os.getenv('POSTGRESS_USER'),
          password=os.getenv('POSTGRESS_PASS', ),
          db=os.getenv('POSTGRESS_DB'),
          ip_type=IPTypes.PUBLIC,
        )
  return conn

At the initialization of the project, it creates users and teams tables, and that's when the above error arises.

**Comment by jackwotherspoon** [comment] 2022-12-09 15:23
Hi @upbrains-admin @aiscience01, thanks for supplying the code sample. I was able to reproduce the issue and am now looking at trying to find the root cause, from my initial triage I don't think the error is within the Python Connector code and is more likely a `pg8000` bug.

I will try investigating a bit more to see if I can find a workaround or solution to the error, in the meantime would you care to raise an issue on the [pg8000 repository](https://github.com/tlocke/pg8000/issues) explaining your issue and see if they have any guidance?

Thanks and have a great day.

**Comment by jackwotherspoon** [comment] 2022-12-12 01:00
@aiscience01  @upbrains-admin Updated my previous comment as it appears this may potentially be a bug in the Python Connector after further investigation. Thanks for raising it, will keep this thread updated as I look into resolving it.

**Comment by aiscience01** [comment] 2022-12-13 22:49
Hi @jackwotherspoon Thank you for the investigation and the follow ups. Yes, using direct TCP connections, we can connect to the db. The connection pool using cloud-sql-python-connector with pg8000 has this issue.

As advised, I raised an issue in pg8000 githib repo for them to investigate as well, and linked this ticket, too: https://github.com/tlocke/pg8000/issues/124

Appreciate your help to be able to use this connector as opposed to direct TCP link.

**Comment by tlocke** [comment] 2022-12-14 15:08
Hi all, this is a bug in pg8000, and it should be fixed in the latest version 1.29.4. Let me know if it's still a problem though.

**Comment by jackwotherspoon** [comment] 2022-12-14 15:49
@tlocke Thanks for the fix! I can confirm that using `pg8000==1.29.4` has resolved the error. 

I will bump the version in this library, thanks again!

**Closed** 2022-12-14 16:17 UTC
Labels: type: bug, priority: p2
