### ISSUE TITLE
How to catch connection errors...

### ISSUE THREAD

**Issue by GodefroyClair** [GoogleCloudPlatform/cloud-sql-python-connector#607] opened 2023-02-09 23:40 UTC
## Question

I am using an Apache Beam streaming pipeline (2.43) coded in Python (2.9) with which I have to - among other things - connect to Cloud SQL (pg). To communicate with Cloud SQL, I use cloud-sql-python-connector as there are no good Dataflow alternative for our case.

During the connection initialization phase, some requests are sent to Cloud SQL Admin server and, sometimes, a spur of connections can occur that make us reach the limit of requests / min to Cloud SQL Admin, which induce receiving "529 too many requests error". This is OK as there is an exponential backoff mechanism to deal with that but our problem is that I haven't found a way to stop the connector from throwing an error in the Dataflow & Cloud logging logs even if all the connection process are surrounded  with a try/except...

```
while connected is False and conn_try <= max_retry:
            try:
                with pool.connect() as conn:
                    connected = True
                    for chunk in chunks:
                        # open a new connection from the pool of connection
                        conn.execute(query, data)
            except Exception as err:
                if conn_try < max_retry:
                    # logging.warning("""CloudSQL Insert - Try nb: %s -
                    #                 will wait for %s sec(s). Error in insert is: %s""",
                    #                 conn_try, int(math.exp(conn_try)), err)
                    time.sleep(math.exp(conn_try) + random.randint(0, 60))
                    conn_try += 1

                else:
                    logging.error("""CloudSQL Insert - Try %s times the following
                                  request without success: %s - error is: %s""",
             
```

The error in Cloud Logging :
```
['prj-cpr-int:europe-west1:cg1-int-bkt-aq098-cpr-cpro-cpp-database-data-cpro-euw1']: An error occurred while performing refresh. Scheduling another refresh attempt immediately Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/google/cloud/sql/connector/instance.py", line 410, in _refresh_task refresh_data = await refresh_task File "/usr/local/lib/python3.9/site-packages/google/cloud/sql/connector/instance.py", line 347, in _perform_refresh ephemeral_cert = await ephemeral_task File "/usr/local/lib/python3.9/site-packages/google/cloud/sql/connector/refresh_utils.py", line 190, in _get_ephemeral resp = await client_session.post( File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 643, in _request resp.raise_for_status() File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status raise ClientResponseError( aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://sqladmin.googleapis.com/sql/v1beta4/projects/prj-cpr-int/instances/cg1-int-bkt-aq098-cpr-cpro-cpp-database-data-cpro-euw1:generateEphemeralCert')
```

My guess is that it is due to the fact that the connector uses an "async" pattern? So the error is thrown asynchronously and can't be caugh in our code ? 
Is there a loop somewhere that execute callbacks where I can stop errors from appearing in cloud logging ?
Could this be related to the usage of the `raise_for_status` parameter in the `aiohttp.ClientSession()` method ?
https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientResponse.raise_for_status

thank you

**Comment by jackwotherspoon** [comment] 2023-02-10 16:47
Hi @GodefroyClair, thanks for raising a question on the Python Connector! 😄

The reason the try/catch doesn't stop the log message is because it is the logger that is logging the exception as seen [here in the code](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/blob/main/google/cloud/sql/connector/instance.py#L396). So even with a try/catch that catches the error itself, the logger will still output the exception message to give details as to where the error occurred before it gets bubbled up to the connector itself. 

So I guess this makes me want to clarify your question. Are you wanting to just suppress the log messages? Is that your goal?

If it is you should just be able to disable the log level for exceptions so that the log messages don't appear in the logs.
I believe the following should do the trick in your application code:
```python
import logging
logging.disable(logging.ERROR)
```

Let me know if this doesn't work and I can try to reproduce your case and find a solution that does. I do want to point out that if you are still getting a lot of 529 errors that may point to an implementation error that may want to be looked at further and resolved to mitigate the exceptions being logged in the first place.

Have a great day!

**Comment by GodefroyClair** [comment] 2023-02-12 16:38
Hi @jackwotherspoon,
Thanks for your answer ! I would like to disable log error yes but only for errors coming from "cloud-sql-python-connector". I didn't investigate but I wonder if  there's a way to do that ?
Regarding the implementation error you are referring to, we have used many things to mitigate the 429 (pool of connections, mutual state accross a worker, exponential backoff...) but as we are also trying to increase the number of workers and threads it is hard to not hit into the quotas of requests per minute (now at 1200) as we have some business rules that require a lot of requests.
The reason is mostely related to the fact that Dataflow has "spurs of connexions" during certain actions.
What would really be great is to avoid the connexion asking for a new certificate each time but I don't think it is possible, isn't it?

**Comment by jackwotherspoon** [comment] 2023-02-13 15:21
@GodefroyClair 

You can disable logging for the Cloud SQL Python Connector just as you would any other module. To do so you can change the log level of the Python Connector logger to `logging.CRITICAL` in your application code, this will suppress all the "An error occurred during ..." `logging.exception` messages you were seeing in your logs.

```python
import logging
logger = logging.getLogger("google.cloud.sql.connector").setLevel(logging.CRITICAL)
```

Let me know if this works for you! 

> What would really be great is to avoid the connexion asking for a new certificate each time but I don't think it is possible, isn't it?

The connector only asks for a new certificate upon initializing a `Connector()` object and then every hour after this to refresh data. I would recommend looking to cache your connector objects so that you are not re-initializing new connectors over and over again for each connection, this is inefficient and most likely why you are running into quota issues. Hopefully caching will help bring down your quota usage and resolve the number of 529 errors you run into.

Have a great day!

**Comment by jackwotherspoon** [comment] 2023-02-13 17:23
Closing this issue as previous comment should resolve logs related question. Thanks for the question and feel free to open a new question if another one is to arise 😄

**Closed by jackwotherspoon** 2023-02-13 17:23 UTC
Labels: type: question, priority: p2
