### ISSUE TITLE
Cannot create connection with asyncpg driver

### ISSUE THREAD

**Issue by martin-wiebusch-thg** [GoogleCloudPlatform/cloud-sql-python-connector#420] opened 2022-08-08 16:04 UTC
## Bug Description

Executing a query with IAM authorization and using the asyncpg driver fails with the following error:

```
AttributeError: 'Connection' object has no attribute 'await_'
```

## Example code (or command)

```python
import asyncio

import sqlalchemy
import sqlalchemy.ext.asyncio
from google.cloud.sql.connector import Connector


def get_async_connection():
    con = Connector().connect(
        'myproject:myzone:myinstance',
        'asyncpg',
        user='me@mycompany.com',
        db='mydb',
        enable_iam_auth=True,
    )
    return con


async def async_main():
    engine = sqlalchemy.ext.asyncio.create_async_engine('postgresql+asyncpg://', creator=get_async_connection)

    async with engine.begin() as conn:
        sql = sqlalchemy.sql.text('SELECT * FROM table LIMIT 5')
        cur = await conn.execute(sql)
        print(cur.fetchall())

    await engine.dispose()


asyncio.run(async_main())

```

Asynchronous queries to a local postgres database (without the connector) work fine. So do synchronous queries using the connector and the pg8000 driver.

## Stacktrace
```
Traceback (most recent call last):
  File "/Users/wiebuschm/.../scratch.py", line 58, in <module>
    asyncio.run(async_main())
  File "/Users/wiebuschm/.pyenv/versions/3.9.13/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/wiebuschm/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/wiebuschm/.../scratch.py", line 24, in async_main
    async with engine.begin() as conn:
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/base.py", line 60, in __aenter__
    return await self.start(is_ctxmanager=True)
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 596, in start
    await self.conn.start(is_ctxmanager=is_ctxmanager)
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 155, in start
    await (greenlet_spawn(self.sync_engine.connect))
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 128, in greenlet_spawn
    result = context.switch(value)
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3234, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3313, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3280, in _wrap_pool_connect
    return fn()
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 677, in __connect
    pool.dispatch.connect.for_modify(
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 329, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 343, in __call__
    fn(*args, **kw)
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 670, in on_connect
    do_on_connect(dbapi_connection)
  File "/Users/wiebuschm/.pyenv/versions/precs/lib/python3.9/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 1101, in connect
    conn.await_(self.setup_asyncpg_json_codec(conn))
AttributeError: 'Connection' object has no attribute 'await_'
```

## How to reproduce

  1. Run the code above

## Environment

1. OS type and version: macOS Montenery 12.5
2. Python version: Python 3.9.13
2. Connector version: cloud-sql-python-connector==0.8.0

**Comment by jackwotherspoon** [comment] 2022-08-08 22:00
Hi @martin-wiebusch-thg, thanks for raising an issue on the Cloud SQL Python Connector!

The issue you are seeing is being caused by two main things I believe:
1.  SQLAlchemy's `create_async_engine` method does not have a `creator` argument like it's synchronous counterpart does [#8215](https://github.com/sqlalchemy/sqlalchemy/issues/8215)
2. The current recommended usage of the Python Connector with `asyncpg` is through the following:
```python
import asyncpg
from google.cloud.sql.connector import create_async_connector

async def main():
    # intialize Connector object using 'create_async_connector'
    connector = await create_async_connector()

    # create connection to Cloud SQL database
    conn: asyncpg.Connection = await connector.connect_async(
        "project:region:instance", # Cloud SQL instance connection name
        "asyncpg",
        user="my-user@company.com",
        db="my-db-name",
        enable_iam_auth=True
        # ... additional database driver args 
    )

    # insert into Cloud SQL database (example)
    await conn.execute("INSERT INTO ratings (title, genre, rating) VALUES ('Batman', 'Action', 8.2)")

    # close asyncpg connection
    await conn.close

    # close Cloud SQL Connector
    await connector.close_async()
```
For full details on connecting using asyncpg, you can check out the [Async Driver Usage](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector#async-driver-usage) section of our README.

I will look at making it more clear that there is a different usage for async drivers in the README by linking to it in synchronous Connector usage section.

Let me know if this helps resolve your issue! If it does I will go ahead and close this issue. Feel free to raise a separate issue or feature request if the above `asyncpg` usage with the Python Connector doesn't fit your needs (i.e support for asyncpg connection pooling). We are always looking for feedback from our users :)

Thanks again for using the Cloud SQL Python Connector and have a great day!

**Comment by martin-wiebusch-thg** [comment] 2022-08-09 08:54
Thanks Jack.

Without SQLAlchemy I no longer have a connection pool, right? I thought that way of using the connector is not recommended (according to your README).

Do any of the workarounds discussed in [#8215](https://github.com/sqlalchemy/sqlalchemy/issues/8215) actually work for our use case? I tried some of them but couldn't get anything to run.

**Comment by jackwotherspoon** [comment] 2022-08-09 15:15
Hi @martin-wiebusch-thg, 

That is correct, we recommend using connection pooling where possible with the Cloud SQL Python Connector as it adds benefits (re-use open connections, reduces overhead, cleans up connections etc.)

I was able to get the following workaround to work for `asyncpg` with SQLAlchemy:
```python
import asyncio
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.util import await_only
from google.cloud.sql.connector import Connector

async def async_creator():
    loop = asyncio.get_running_loop()
    async with Connector(loop=loop) as connector:
        conn = await connector.connect_async(
            "project:region:instance", # Cloud SQL instance connection name"
            "asyncpg",
            user="my-db-user",
            password="my-db-password",
            db="my-db-name",
        )
        return conn

async def async_main():
    def adapted_creator():
        dbapi = engine.dialect.dbapi
        from sqlalchemy.dialects.postgresql.asyncpg import (
            AsyncAdapt_asyncpg_connection,
)
        return AsyncAdapt_asyncpg_connection(
            dbapi,
            await_only(async_creator()),
            prepared_statement_cache_size=100,
        )

    # create async connection pool with wrapped creator
    engine = create_async_engine(
        "postgresql+asyncpg://",
        echo=True,
        creator=adapted_creator,
    )
    
    # use connection pooling with Cloud SQL Python Connector
    async with engine.connect() as conn:
        query = await conn.execute(text("SELECT * from ratings"))
        results = query.fetchall()
        for row in results:
            print(row)


asyncio.run(async_main())
```
As you can see it is not the prettiest and most straightforward implementation of connection pooling (which is why we currently do not showcase it in our README)

I have gone ahead and opened #422 to either document this workaround (or a better one) for connection pooling in our README, or to support and return connection pools for async drivers natively from the Python Connector.

Let me know if this has resolved your issue and I will go ahead and close out this issue. 

Thanks again for showing interest in making the Cloud SQL Python Connector better! Enjoy your day :)

**Comment by martin-wiebusch-thg** [comment] 2022-08-15 08:36
Thanks Jack. Tried it and it works! I agree it's a bit ugly but the ugliness can easily be hidden inside a function. In fact, I was wondering why you don't simply provide, as part of the connector package, functions `create_engine` and `create_async_engine` which return suitably initialised SQLAlchemy engine objects. That would also reduce the boilerplate you need for the synchonous use case. You could have SQLAlchemy as an optional dependency so that the package can still be installed without SQLAlchemy if needed.

**Comment by jackwotherspoon** [comment] 2022-08-15 13:47
Hi @martin-wiebusch-thg,

Glad it worked for you! That is a great suggestion about maybe hiding the SQLAlchemy section all together and have the Connector take care of creating the connection pool internally. I will talk this suggestion over with the team and include any updates or outcomes on issue #422 

We want to make sure that the Connector can still be used with other ORMs other than just SQLAlchemy, but you are right that if we are going to recommend SQLAlchemy for all our connections maybe we can add functionality to the Connector to facilitate this! From a user's perspective I think it is a very useful feature :) 

Will close out this issue now that you have it working. Thanks again for your interest and use of the Cloud SQL Python Connector!

**Closed by jackwotherspoon** 2022-08-15 13:47 UTC
Labels: type: bug

**Comment by jackwotherspoon** [comment] 2022-08-15 19:51
@martin-wiebusch-thg

FYI: I have started a WIP PR #428  to look into having the connection pools created internally to reduce code required for users to connect. ;)
